In [70]:
import pandas as pd

### Game Events

Objectives:
- what's the JSON schema

In [71]:
from audl.stats.endpoints.gamestats import GameStats

GAMEID = "2022-07-31-DET-MIN"
game = GameStats(GAMEID)
game_json = game.json

In [72]:
game_json.keys()

dict_keys(['game', 'rostersHome', 'rostersAway', 'tsgHome', 'tsgAway'])

In [73]:
game_json['game']

{'id': 2874,
 'team_season_id_home': 229,
 'team_season_id_away': 232,
 'status_id': 100,
 'score_home': 28,
 'score_away': 9,
 'live': None,
 'reg_season': True,
 'ignore_game': False,
 'lock': True,
 'start_timestamp': '2022-07-31T17:00:00.000Z',
 'start_timezone': 'CDT',
 'start_time_tbd': None,
 'aw_section': 'week-14',
 'score_times_home': [0,
  356,
  416,
  494,
  720,
  750,
  943,
  1102,
  1210,
  1288,
  1343,
  1405,
  1419,
  1531,
  1607,
  2046,
  2086,
  2116,
  2156,
  2191,
  2299,
  2520,
  2575,
  2631,
  2648,
  2677,
  2761,
  2789,
  2880],
 'score_times_away': [0, 640, 803, 865, 973, 1377, 1506, 1646, 2429, 2853],
 'ext_game_id': '2022-07-31-DET-MIN',
 'update_timestamp': '2024-05-22T23:28:09.125Z',
 'location_id': 34,
 'ls_game_id': '533620d0-0ab8-48f6-a3f4-30c782861abe',
 'ticket_url': 'https://shop.windchillultimate.com/collections/tickets',
 'streaming_url': 'https://audltv.vhx.tv/videos/detroit-at-minnesota-07-31-2022',
 'roster_set': True,
 'roster_set_1': True,
 'type_id': 1,
 'team_season_home': {'id': 229,
  'team_id': 12,
  'season_id': 13,
  'division_id': 6,
  'city': 'Minnesota',
  'abbrev': 'MIN',
  'ulti_analytics_ext_id': None,
  'final_standing': 2,
  'team': {'id': 12,
   'name': 'Wind Chill',
   'ext_team_id': 'windchill',
   'ls_team_id': '1a030718-20cc-44ee-96a5-c92621cab7b3',
   'active': True,
   'primary_hex': '#6F7F98',
   'secondary_hex': '#000000'}},
 'team_season_away': {'id': 232,
  'team_id': 6,
  'season_id': 13,
  'division_id': 6,
  'city': 'Detroit',
  'abbrev': 'DET',
  'ulti_analytics_ext_id': None,
  'final_standing': 6,
  'team': {'id': 6,
   'name': 'Mechanix',
   'ext_team_id': 'mechanix',
   'ls_team_id': 'c55ccc57-2434-479b-ade2-9d876b37ab17',
   'active': True,
   'primary_hex': '#660000',
   'secondary_hex': '#000000'}}}

In [74]:
game_json['game'].keys()

dict_keys(['id', 'team_season_id_home', 'team_season_id_away', 'status_id', 'score_home', 'score_away', 'live', 'reg_season', 'ignore_game', 'lock', 'start_timestamp', 'start_timezone', 'start_time_tbd', 'aw_section', 'score_times_home', 'score_times_away', 'ext_game_id', 'update_timestamp', 'location_id', 'ls_game_id', 'ticket_url', 'streaming_url', 'roster_set', 'roster_set_1', 'type_id', 'team_season_home', 'team_season_away'])

In [75]:
game_json['rostersHome']

[{'id': 9964,
  'team_season_id': 229,
  'player_id': 2485,
  'jersey_number': '0',
  'active': True,
  'player': {'id': 2485,
   'first_name': 'Rocco',
   'last_name': 'Linehan',
   'ext_player_id': 'rlinehan',
   'ls_player_id': 'a1d54cbc-f7ef-4e21-a01b-b872d46e4145'}},
 {'id': 9965,
  'team_season_id': 229,
  'player_id': 2608,
  'jersey_number': '1',
  'active': True,
  'player': {'id': 2608,
   'first_name': 'William',
   'last_name': 'Brandt',
   'ext_player_id': 'wbrandt',
   'ls_player_id': 'd5996a64-11e3-4296-a17d-17e9b9869ad8'}},
 {'id': 9966,
  'team_season_id': 229,
  'player_id': 2609,
  'jersey_number': '2',
  'active': True,
  'player': {'id': 2609,
   'first_name': 'Bret',
   'last_name': 'Bergmeier',
   'ext_player_id': 'bbergmeie',
   'ls_player_id': '2a818fa0-3906-4c36-b997-53667d8db185'}},
 {'id': 9967,
  'team_season_id': 229,
  'player_id': 273,
  'jersey_number': '3',
  'active': True,
  'player': {'id': 273,
   'first_name': 'Bryan',
   'last_name': 'Vohnoutka',
   'ext_player_id': 'bvohnoutk',
   'ls_player_id': '6904f7bf-c0fa-49e3-8083-c5b748a3eab4'}},
 {'id': 9968,
  'team_season_id': 229,
  'player_id': 1968,
  'jersey_number': '4',
  'active': True,
  'player': {'id': 1968,
   'first_name': 'Sam',
   'last_name': 'Ward',
   'ext_player_id': 'sward',
   'ls_player_id': '545357c1-cc17-4b21-a1a6-9445fef04a83'}},
 {'id': 9969,
  'team_season_id': 229,
  'player_id': 955,
  'jersey_number': '5',
  'active': True,
  'player': {'id': 955,
   'first_name': 'Jordan',
   'last_name': 'Taylor',
   'ext_player_id': 'jtaylor',
   'ls_player_id': 'a1ad2111-ccfc-4635-9034-d52068d624b8'}},
 {'id': 9970,
  'team_season_id': 229,
  'player_id': 12,
  'jersey_number': '6',
  'active': True,
  'player': {'id': 12,
   'first_name': 'Abe',
   'last_name': 'Coffin',
   'ext_player_id': 'acoffin',
   'ls_player_id': '86147b10-bb4d-40f4-8a85-8c81977bf821'}},
 {'id': 9971,
  'team_season_id': 229,
  'player_id': 2360,
  'jersey_number': '7',
  'active': True,
  'player': {'id': 2360,
   'first_name': 'Tyler',
   'last_name': 'Thomegreene',
   'ext_player_id': 'tthomegre',
   'ls_player_id': '2a5d2602-7792-4dac-8727-32d615e18433'}},
 {'id': 9972,
  'team_season_id': 229,
  'player_id': 2486,
  'jersey_number': '8',
  'active': True,
  'player': {'id': 2486,
   'first_name': 'Nick',
   'last_name': 'Vogt',
   'ext_player_id': 'nvogt',
   'ls_player_id': 'e0a8cba7-8ff8-419b-a5c4-c422e1d74567'}},
 {'id': 9973,
  'team_season_id': 229,
  'player_id': 2488,
  'jersey_number': '9',
  'active': True,
  'player': {'id': 2488,
   'first_name': 'Sebastian',
   'last_name': 'Brauer',
   'ext_player_id': 'sbrauer',
   'ls_player_id': '6ff886f4-d0c4-488a-a6e0-f850230d2aff'}},
 {'id': 9974,
  'team_season_id': 229,
  'player_id': 1284,
  'jersey_number': '10',
  'active': True,
  'player': {'id': 1284,
   'first_name': 'Michael',
   'last_name': 'Jordan',
   'ext_player_id': 'mjordan',
   'ls_player_id': '69ba6357-d45d-490d-b620-01754dfd19db'}},
 {'id': 9975,
  'team_season_id': 229,
  'player_id': 1919,
  'jersey_number': '11',
  'active': True,
  'player': {'id': 1919,
   'first_name': 'Josh',
   'last_name': 'Kautz',
   'ext_player_id': 'jkautz',
   'ls_player_id': 'e6870f26-1565-45f3-aeb3-ce93b4e2e13f'}},
 {'id': 9976,
  'team_season_id': 229,
  'player_id': 2841,
  'jersey_number': '12',
  'active': True,
  'player': {'id': 2841,
   'first_name': 'Marty',
   'last_name': 'Adams',
   'ext_player_id': 'madams',
   'ls_player_id': '83ced919-5a41-4d3d-96a2-265c87298083'}},
 {'id': 9977,
  'team_season_id': 229,
  'player_id': 1916,
  'jersey_number': '13',
  'active': True,
  'player': {'id': 1916,
   'first_name': 'Cole',
   'last_name': 'Jurek',
   'ext_player_id': 'cjurek',
   'ls_player_id': '5cb6418e-2d23-486e-928f-7473d98c6209'}},
 {'id': 9978,
  'team_season_id': 229,
  'player_id': 2487,
  'jersey_number': '14',
  'active': True,
  'player': {'id': 2487,
   'first_name': 'Ian',
   'last_name': 'Hahn',
   'ext_player_id': 'ihahn',
   'ls_player_id': 'eb626b51-5d2c-41b6-a447-19982d582457'}},
 {'id': 9979,
  'team_season_id': 229,
  'player_id': 1920,
  'jersey_number': '15',
  'active': True,
  'player': {'id': 1920,
   'first_name': 'Kristian',
   'last_name': 'Johnson',
   'ext_player_id': 'kjohnson1',
   'ls_player_id': '3180524d-8105-4f28-996c-3b4bde22dacf'}},
 {'id': 9980,
  'team_season_id': 229,
  'player_id': 2610,
  'jersey_number': '16',
  'active': True,
  'player': {'id': 2610,
   'first_name': 'Brandon',
   'last_name': 'Lafferty',
   'ext_player_id': 'blafferty',
   'ls_player_id': '4591c028-9a81-499a-85b8-02d74075f9dc'}},
 {'id': 9981,
  'team_season_id': 229,
  'player_id': 1918,
  'jersey_number': '17',
  'active': True,
  'player': {'id': 1918,
   'first_name': 'Isaac',
   'last_name': 'Leonard',
   'ext_player_id': 'ileonard',
   'ls_player_id': 'd888fe58-d828-4258-8eb8-c50e9f6ef89d'}},
 {'id': 9982,
  'team_season_id': 229,
  'player_id': 2842,
  'jersey_number': '18',
  'active': True,
  'player': {'id': 2842,
   'first_name': 'Gordon',
   'last_name': 'Larson',
   'ext_player_id': 'glarson',
   'ls_player_id': '54d07c23-44ee-492c-b150-14677b8e9880'}},
 {'id': 9983,
  'team_season_id': 229,
  'player_id': 2843,
  'jersey_number': '20',
  'active': True,
  'player': {'id': 2843,
   'first_name': 'Luke',
   'last_name': 'Bleers',
   'ext_player_id': 'lbleers',
   'ls_player_id': 'f7c23af4-0818-43dd-9ae4-8ac33b400802'}},
 {'id': 9984,
  'team_season_id': 229,
  'player_id': 2179,
  'jersey_number': '22',
  'active': True,
  'player': {'id': 2179,
   'first_name': 'Rami',
   'last_name': 'Paust',
   'ext_player_id': 'rpaust',
   'ls_player_id': 'cc23a412-b9ab-499c-b7c6-203f4f450977'}},
 {'id': 9985,
  'team_season_id': 229,
  'player_id': 2770,
  'jersey_number': '23',
  'active': True,
  'player': {'id': 2770,
   'first_name': 'Paul',
   'last_name': 'Krenik',
   'ext_player_id': 'pkrenik',
   'ls_player_id': 'fec0298b-cc71-43d4-8b0a-f5d199997674'}},
 {'id': 9986,
  'team_season_id': 229,
  'player_id': 389,
  'jersey_number': '24',
  'active': True,
  'player': {'id': 389,
   'first_name': 'Colin',
   'last_name': 'Berry',
   'ext_player_id': 'cberry',
   'ls_player_id': '97230907-59b1-46e7-a692-53ed09b6022f'}},
 {'id': 9987,
  'team_season_id': 229,
  'player_id': 973,
  'jersey_number': '29',
  'active': True,
  'player': {'id': 973,
   'first_name': 'Josh',
   'last_name': 'Klane',
   'ext_player_id': 'jklane',
   'ls_player_id': 'a16b5cef-28e5-46f2-97b1-cc3e5081b3f0'}},
 {'id': 9988,
  'team_season_id': 229,
  'player_id': 2611,
  'jersey_number': '32',
  'active': True,
  'player': {'id': 2611,
   'first_name': 'Andrew',
   'last_name': 'Roy',
   'ext_player_id': 'aroy',
   'ls_player_id': '930e1f79-f3df-4e11-918a-077c8cddd256'}},
 {'id': 9989,
  'team_season_id': 229,
  'player_id': 784,
  'jersey_number': '34',
  'active': True,
  'player': {'id': 784,
   'first_name': 'James',
   'last_name': 'Kittlesen',
   'ext_player_id': 'jkittlese',
   'ls_player_id': '2103345b-ddf2-4653-8b60-84d20396110f'}},
 {'id': 9990,
  'team_season_id': 229,
  'player_id': 2844,
  'jersey_number': '47',
  'active': True,
  'player': {'id': 2844,
   'first_name': 'Mickey',
   'last_name': 'Walsh',
   'ext_player_id': 'mwalsh',
   'ls_player_id': 'a9dff6a7-68a5-422d-bdf6-0c5779111812'}},
 {'id': 9991,
  'team_season_id': 229,
  'player_id': 562,
  'jersey_number': '54',
  'active': True,
  'player': {'id': 562,
   'first_name': 'Dylan',
   'last_name': 'DeClerck',
   'ext_player_id': 'ddeclerck',
   'ls_player_id': '715cc2b2-40a5-4582-9f10-10d7608ffcae'}},
 {'id': 9992,
  'team_season_id': 229,
  'player_id': 221,
  'jersey_number': '61',
  'active': True,
  'player': {'id': 221,
   'first_name': 'Brandon',
   'last_name': 'Matis',
   'ext_player_id': 'bmatis',
   'ls_player_id': '4620826f-d394-4491-8455-5cbb2251c4bd'}},
 {'id': 9993,
  'team_season_id': 229,
  'player_id': 1753,
  'jersey_number': '94',
  'active': True,
  'player': {'id': 1753,
   'first_name': 'Tony',
   'last_name': 'Poletto',
   'ext_player_id': 'tpoletto',
   'ls_player_id': 'e96cc8b7-179b-4221-adc9-c981c2b5eabb'}},
 {'id': 9994,
  'team_season_id': 229,
  'player_id': 2249,
  'jersey_number': '98',
  'active': True,
  'player': {'id': 2249,
   'first_name': 'Quinn',
   'last_name': 'Snider',
   'ext_player_id': 'qsnider',
   'ls_player_id': '3b398ae1-5611-444b-99c7-d0ce17bafeff'}},
 {'id': 9995,
  'team_season_id': 229,
  'player_id': 2845,
  'jersey_number': '99',
  'active': True,
  'player': {'id': 2845,
   'first_name': 'Tristan',
   'last_name': 'Van de Moortele',
   'ext_player_id': 'tvandemoo',
   'ls_player_id': 'caee46d5-b247-49b6-a63d-1ee8c31cd962'}},
 {'id': 10657,
  'team_season_id': 229,
  'player_id': 3110,
  'jersey_number': '26',
  'active': True,
  'player': {'id': 3110,
   'first_name': 'Marco',
   'last_name': 'Dregni',
   'ext_player_id': 'mdregni',
   'ls_player_id': 'fb2d4a45-7305-44b0-bdd2-74fb0d66ba8e'}},
 {'id': 10658,
  'team_season_id': 229,
  'player_id': 3111,
  'jersey_number': '44',
  'active': True,
  'player': {'id': 3111,
   'first_name': 'Noah',
   'last_name': 'Hanson',
   'ext_player_id': 'nhanson',
   'ls_player_id': '1e437125-860b-42c3-87a9-23d8f378182e'}},
 {'id': 10716,
  'team_season_id': 229,
  'player_id': 3142,
  'jersey_number': '80',
  'active': True,
  'player': {'id': 3142,
   'first_name': 'Tucker',
   'last_name': 'Hoffman',
   'ext_player_id': 'thoffman',
   'ls_player_id': 'fa32d2d9-3140-4d3e-8978-1da3616e20ca'}}]

In [76]:
game_json['tsgHome'].keys()

dict_keys(['id', 'teamSeasonId', 'gameId', 'source', 'startOnOffense', 'events', 'updateMoment', 'statusId', 'scoreTimesOur', 'scoreTimesTheir', 'completionsNumer', 'completionsDenom', 'hucksNumer', 'hucksDenom', 'blocks', 'turnovers', 'oLineScores', 'oLinePoints', 'oLinePossessions', 'dLineScores', 'dLinePoints', 'dLinePossessions', 'redZoneScores', 'redZonePossessions', 'isHome', 'rosterIds'])

### Player metadata

In [77]:
import requests
from bs4 import BeautifulSoup

In [78]:
url = "https://www.watchufa.com/league/players/mmcdonnel"

In [79]:
t = requests.get(url)

In [86]:
url2 = "https://www.watchufa.com/league/players/abartlett"
t1 = requests.get(url2)

In [87]:
soup = BeautifulSoup(t1.text)

In [88]:
# soup.prettify()

In [89]:
# soup.find("div", {"id": "content"})

In [90]:
name = soup.find('div', class_='audl-player-display-name').text.strip()
team_position = soup.find('div', class_='audl-player-current-team-position').text.strip()
jersey_number = soup.find('div', class_='audl-player-jersey-number').text.strip()
# team = team_position.split('/')[0]
# position = team_position.split('/')[1]

# Extract personal stats
stats = {}
for item in soup.find_all('div', class_='audl-personal-stats-item'):
    label = item.find('span', class_='audl-personal-stats-label').text.strip()
    value = item.find('span', class_='audl-personal-stats-value').text.strip()
    stats[label] = value

# Extract player bio text and hometown
bio_paragraphs = soup.select('.audl-player-bio-text p')
bio_text = ' '.join([p.text for p in bio_paragraphs if 'Hometown:' not in p.text])
hometown = ''
for p in bio_paragraphs:
    if 'Hometown:' in p.text:
        hometown = p.text.split('Hometown:')[-1].strip()

# Combine all into a dictionary
player_data = {
    'Name': name,
    'Team': team,
    'Team / Position': team_position, 
    # 'Position': position,
    'Jersey Number': jersey_number,
    'Height': stats.get('HEIGHT'),
    'Weight': stats.get('WEIGHT'),
    'DOB': stats.get('AGE/DOB'),
    'College': stats.get('COLLEGE'),
    'Hometown': hometown,
    'Bio': bio_text
}

# Convert to DataFrame
df = pd.DataFrame([player_data])
# print(df)

In [85]:
player_data

{'Name': 'Aaron Bartlett',
 'Team': 'DC Breeze',
 'Jersey Number': '#14',
 'Height': None,
 'Weight': None,
 'DOB': None,
 'College': None,
 'Hometown': '',
 'Bio': ''}

In [32]:
df

,Name,Team,Position,Jersey Number,Height,Weight,DOB,College,Hometown,Bio
0,Rowan McDonnell,DC Breeze,Hybrid,#12,"6'0""",170,"June 1, 1989",Tidewater Community College,"Niantic, CT",Rowan McDonnell was born and raised in Connect...

### Season Schedule

In [91]:
from audl.stats.endpoints.seasonschedule import SeasonSchedule, TeamSeasonSchedule, AllSchedule, TeamSeasonAgainstOpponentSchedule

# Fetch complete season schedule from "https://theaudl.com/league/game-search"

season_schedule = SeasonSchedule(2023).get_schedule()

https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=1
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=2
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=3
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=4
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=5
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=6
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=7
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=8
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=9
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=10
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=11
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=12
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=13
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=14
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=15
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=16
https://www.backend.ufastats.com/web-v1/games?limit=10&years=2023&page=17

In [92]:
season_schedule.columns

Index(['gameID', 'awayTeamID', 'awayTeamCity', 'awayTeamName',
       'awayTeamNameRaw', 'homeTeamID', 'homeTeamCity', 'homeTeamName',
       'homeTeamNameRaw', 'awayScore', 'homeScore', 'status', 'week',
       'ticketURL', 'streamingURL', 'hasRosterReport', 'locationName',
       'locationURL', 'startTimestamp', 'startTimezone', 'startTimeTBD'],
      dtype='object')

In [94]:
# season_schedule.head(n=0).to_sql()

In [69]:
season_schedule.head()

,gameID,awayTeamID,awayTeamCity,awayTeamName,awayTeamNameRaw,homeTeamID,homeTeamCity,homeTeamName,homeTeamNameRaw,awayScore,...,status,week,ticketURL,streamingURL,hasRosterReport,locationName,locationURL,startTimestamp,startTimezone,startTimeTBD
0,2023-08-26-SLC-NY,shred,Salt Lake,Shred,Shred,empire,New York,Empire,Empire,12,...,Final,semi-finals,None,None,False,None,None,2023-08-26T18:00:00-05:00,CDT,False
1,2023-08-25-MIN-SLC,windchill,Minnesota,Wind Chill,Wind Chill,shred,Salt Lake,Shred,Shred,18,...,Final,semi-finals,https://shop.theaudl.com/collections/champions...,https://audltv.vhx.tv/videos/minnesota-vs-salt...,False,TCO Stadium,None,2023-08-25T19:30:00-05:00,CDT,False
2,2023-08-25-ATX-NY,sol,Austin,Sol,Sol,empire,New York,Empire,Empire,17,...,Final,semi-finals,https://shop.theaudl.com/collections/champions...,https://audltv.vhx.tv/videos/austin-vs-new-yor...,False,TCO Stadium,,2023-08-25T17:00:00-05:00,CDT,False
3,2023-08-12-DC-NY,breeze,DC,Breeze,Breeze,empire,New York,Empire,Empire,19,...,Final,divisional-champ,None,https://audltv.vhx.tv/videos/dc-at-new-york-08...,False,Joseph F. Fosina Field,https://watchufa.com/empire/stadium,2023-08-12T19:00:00-04:00,EDT,False
4,2023-08-12-IND-MIN,alleycats,Indianapolis,AlleyCats,AlleyCats,windchill,Minnesota,Wind Chill,Wind Chill,18,...,Final,divisional-champ,None,https://audltv.vhx.tv/videos/indianapolis-at-m...,False,Sea Foam Stadium,https://watchufa.com/windchill/stadium-1,2023-08-12T18:00:00-05:00,CDT,False

In [95]:
df = pd.DataFrame([
    {'gameID': 1, 'name': 'Game One', 'date': '2025-04-10'},
    {'gameID': 2, 'name': 'Game Two', 'date': '2025-04-11'},
])

records = df.to_dict(orient='records')

In [96]:
records

[{'gameID': 1, 'name': 'Game One', 'date': '2025-04-10'},
 {'gameID': 2, 'name': 'Game Two', 'date': '2025-04-11'}]

In [98]:
season_schedule['awayTeamID'].unique()

array(['shred', 'windchill', 'sol', 'breeze', 'alleycats', 'aviators',
       'flyers', 'union', 'glory', 'legion', 'mechanix', 'royal', 'rush',
       'spiders', 'steel', 'radicals', 'thunderbirds', 'growlers',
       'empire', 'hustle', 'havoc', 'phoenix', 'summit', 'cascades'],
      dtype=object)

In [100]:
df.columns.tolist()

['gameID', 'name', 'date']

In [102]:
' '.join(df.iterrows())

TypeError: sequence item 0: expected str instance, tuple found

### Upsert

In [104]:
from sqlalchemy import Table, Column, Integer, String, Boolean, MetaData
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.sql import literal_column

metadata = MetaData()

distributors = Table(
    "distributors", metadata,
    Column("did", Integer, primary_key=True),
    Column("dname", String),
    Column("is_active", Boolean, default=True)
)

row = {"did": 10, "dname": "Conrad International"}

# Build base insert
stmt = insert(distributors).values(**row)

# Dynamically build the SET clause (exclude primary key)
update_dict = {
    k: getattr(stmt.excluded, k)
    for k in row.keys()
    if k != "did"  # assuming 'did' is the conflict target / PK
}

# Create upsert statement with WHERE clause on conflict
upsert_stmt = stmt.on_conflict_do_update(
    index_elements=["did"],
    index_where=literal_column("is_active"),  # Partial index condition
    set_=update_dict
)

# Execute
with engine.begin() as conn:
    conn.execute(upsert_stmt)

NameError: name 'engine' is not defined

In [106]:
season_schedule.columns

Index(['gameID', 'awayTeamID', 'awayTeamCity', 'awayTeamName',
       'awayTeamNameRaw', 'homeTeamID', 'homeTeamCity', 'homeTeamName',
       'homeTeamNameRaw', 'awayScore', 'homeScore', 'status', 'week',
       'ticketURL', 'streamingURL', 'hasRosterReport', 'locationName',
       'locationURL', 'startTimestamp', 'startTimezone', 'startTimeTBD'],
      dtype='object')

### Playwright

In [109]:
from playwright.sync_api import sync_playwright

def scrape_players():
    with sync_playwright() as p:
        # Launch a browser instance (headless mode for faster scraping)
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        
        # Navigate to the target URL
        page.goto("https://www.watchufa.com/league/players")
        
        # Wait for the page to load fully (adjust selector if needed)
        page.wait_for_selector("table")  # Assuming data is in a table
        
        # Extract player data
        rows = page.query_selector_all("table tr")
        players = []
        
        for row in rows[1:]:  # Skip header row
            columns = row.query_selector_all("td")
            player_name = columns[0].inner_text()
            recent_team = columns[1].inner_text()
            players.append({"Player": player_name, "Most Recent Team": recent_team})
        
        browser.close()
        return players

# Execute the function and print results
players_data = scrape_players()
for player in players_data:
    print(player)

RuntimeError: asyncio.run() cannot be called from a running event loop

In [110]:
import asyncio
from playwright.async_api import async_playwright

async def scrape_players():
    async with async_playwright() as p:
        # Launch a browser instance (headless mode for faster scraping)
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        
        # Navigate to the target URL
        await page.goto("https://www.watchufa.com/league/players")
        
        # Wait for the page to load fully (adjust selector if needed)
        await page.wait_for_selector("table")  # Assuming data is in a table
        
        # Extract player data
        rows = await page.query_selector_all("table tr")
        players = []
        
        for row in rows[1:]:  # Skip header row
            columns = await row.query_selector_all("td")
            player_name = await columns[0].inner_text()
            recent_team = await columns[1].inner_text()
            players.append({"Player": player_name, "Most Recent Team": recent_team})
        
        await browser.close()
        return players

# Run the async function
async def main():
    players_data = await scrape_players()
    for player in players_data:
        print(player)

# Start asyncio event loop
asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop