In [1]:
import pandas as pd

In [10]:
import os
import inspect
import sys

# currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
# parentdir = os.path.dirname(currentdir)
# grandparent = os.path.dirname(parentdir)
sys.path.insert(0, '/Users/emulie/Projects/audl-analytics/')

In [11]:
from src.utils.mongodb.connections import get_mongo_document

In [40]:
from sqlalchemy import create_engine


engine = create_engine('sqlite:///:memory:')

In [13]:
ext_game_id = '2024-08-24-CAR-MIN'
COLLECTION_NAME = "game-events"
query = {"game.ext_game_id": ext_game_id}
document = get_mongo_document(COLLECTION_NAME, query)

In [17]:
document.keys()

dict_keys(['_id', 'game', 'rostersAway', 'rostersHome', 'tsgAway', 'tsgHome'])

In [54]:
game = document['game']
df_game = pd.json_normalize(document['game'])

In [21]:
df_game.head()

,id,team_season_id_home,team_season_id_away,status_id,score_home,score_away,live,reg_season,ignore_game,lock,...,team_season_away.abbrev,team_season_away.ulti_analytics_ext_id,team_season_away.final_standing,team_season_away.team.id,team_season_away.team.name,team_season_away.team.ext_team_id,team_season_away.team.ls_team_id,team_season_away.team.active,team_season_away.team.primary_hex,team_season_away.team.secondary_hex
0,3460,292,295,100,17,16,False,True,False,False,...,CAR,None,1,18,Flyers,flyers,f364b191-1101-4c86-959e-7ac9b2a0909b,True,#003049,#C0C0C0

In [34]:
df_game.columns

Index(['id', 'team_season_id_home', 'team_season_id_away', 'status_id',
       'score_home', 'score_away', 'live', 'reg_season', 'ignore_game', 'lock',
       'start_timestamp', 'start_timezone', 'start_time_tbd', 'aw_section',
       'score_times_home', 'score_times_away', 'ext_game_id',
       'update_timestamp', 'location_id', 'ls_game_id', 'ticket_url',
       'streaming_url', 'roster_set', 'roster_set_1', 'type_id',
       'team_season_home.id', 'team_season_home.team_id',
       'team_season_home.season_id', 'team_season_home.division_id',
       'team_season_home.city', 'team_season_home.abbrev',
       'team_season_home.ulti_analytics_ext_id',
       'team_season_home.final_standing', 'team_season_home.team.id',
       'team_season_home.team.name', 'team_season_home.team.ext_team_id',
       'team_season_home.team.ls_team_id', 'team_season_home.team.active',
       'team_season_home.team.primary_hex',
       'team_season_home.team.secondary_hex', 'team_season_away.id',
       'team_season_away.team_id', 'team_season_away.season_id',
       'team_season_away.division_id', 'team_season_away.city',
       'team_season_away.abbrev', 'team_season_away.ulti_analytics_ext_id',
       'team_season_away.final_standing', 'team_season_away.team.id',
       'team_season_away.team.name', 'team_season_away.team.ext_team_id',
       'team_season_away.team.ls_team_id', 'team_season_away.team.active',
       'team_season_away.team.primary_hex',
       'team_season_away.team.secondary_hex'],
      dtype='object')

In [94]:
# df_game.to_sql('test', con=engine, if_exists='replace', index=True)

In [38]:
df_game.dtypes

id                                         int64
team_season_id_home                        int64
team_season_id_away                        int64
status_id                                  int64
score_home                                 int64
score_away                                 int64
live                                        bool
reg_season                                  bool
ignore_game                                 bool
lock                                        bool
start_timestamp                           object
start_timezone                            object
start_time_tbd                              bool
aw_section                                object
score_times_home                          object
score_times_away                          object
ext_game_id                               object
update_timestamp                          object
location_id                                int64
ls_game_id                                object
ticket_url                                object
streaming_url                             object
roster_set                                  bool
roster_set_1                                bool
type_id                                    int64
team_season_home.id                        int64
team_season_home.team_id                   int64
team_season_home.season_id                 int64
team_season_home.division_id               int64
team_season_home.city                     object
team_season_home.abbrev                   object
team_season_home.ulti_analytics_ext_id    object
team_season_home.final_standing            int64
team_season_home.team.id                   int64
team_season_home.team.name                object
team_season_home.team.ext_team_id         object
team_season_home.team.ls_team_id          object
team_season_home.team.active                bool
team_season_home.team.primary_hex         object
team_season_home.team.secondary_hex       object
team_season_away.id                        int64
team_season_away.team_id                   int64
team_season_away.season_id                 int64
team_season_away.division_id               int64
team_season_away.city                     object
team_season_away.abbrev                   object
team_season_away.ulti_analytics_ext_id    object
team_season_away.final_standing            int64
team_season_away.team.id                   int64
team_season_away.team.name                object
team_season_away.team.ext_team_id         object
team_season_away.team.ls_team_id          object
team_season_away.team.active                bool
team_season_away.team.primary_hex         object
team_season_away.team.secondary_hex       object
dtype: object

In [43]:
df_rostersHome = pd.json_normalize(document['rostersHome'])

In [44]:
df_rostersHome.head()

,id,team_season_id,player_id,jersey_number,active,player.id,player.first_name,player.last_name,player.ext_player_id,player.ls_player_id
0,11721,292,2609,0,True,2609,Bret,Bergmeier,bbergmeie,2a818fa0-3906-4c36-b997-53667d8db185
1,11722,292,2608,1,True,2608,William,Brandt,wbrandt,d5996a64-11e3-4296-a17d-17e9b9869ad8
2,11723,292,273,3,True,273,Bryan,Vohnoutka,bvohnoutk,6904f7bf-c0fa-49e3-8083-c5b748a3eab4
3,11724,292,3111,4,True,3111,Noah,Hanson,nhanson,1e437125-860b-42c3-87a9-23d8f378182e
4,11725,292,955,5,True,955,Jordan,Taylor,jtaylor,a1ad2111-ccfc-4635-9034-d52068d624b8

In [46]:
pd.io.sql.get_schema(df_rostersHome, 'data')

'CREATE TABLE "data" (\n"id" INTEGER,\n  "team_season_id" INTEGER,\n  "player_id" INTEGER,\n  "jersey_number" TEXT,\n  "active" INTEGER,\n  "player.id" INTEGER,\n  "player.first_name" TEXT,\n  "player.last_name" TEXT,\n  "player.ext_player_id" TEXT,\n  "player.ls_player_id" TEXT\n)'

In [26]:
df_rostersAway = pd.json_normalize(document['rostersAway'])

In [27]:
df_rostersAway.head()

,id,team_season_id,player_id,jersey_number,active,player.id,player.first_name,player.last_name,player.ext_player_id,player.ls_player_id
0,12108,295,3403,0,True,3403,Matthew,Nightingale,mnighting,925da72e-7ed6-4ab7-8707-44552b4e8fc3
1,12109,295,3247,1,True,3247,Tobias,Brooks,tbrooks1,7092a4bf-5e46-472a-8d7a-335a9696b7f8
2,12110,295,1643,2,True,1643,Sol,Yanuck,syanuck,4338c80e-2abd-40e8-a32a-0b95e347aba3
3,12111,295,2202,3,True,2202,Henry,Fisher,hfisher,11f32b4c-e98a-43b0-96fa-619e06d415af
4,12112,295,2222,4,True,2222,Seth,Weaver,sweaver,3264b70f-0b34-4733-a3e7-56173decc733

In [33]:
df_rostersAway.columns

Index(['id', 'team_season_id', 'player_id', 'jersey_number', 'active',
       'player.id', 'player.first_name', 'player.last_name',
       'player.ext_player_id', 'player.ls_player_id'],
      dtype='object')

In [30]:
tsgHome = pd.json_normalize(document['tsgHome'])

In [32]:
tsgHome.columns

Index(['id', 'teamSeasonId', 'gameId', 'source', 'startOnOffense', 'events',
       'updateMoment', 'statusId', 'scoreTimesOur', 'scoreTimesTheir',
       'completionsNumer', 'completionsDenom', 'hucksNumer', 'hucksDenom',
       'blocks', 'turnovers', 'oLineScores', 'oLinePoints', 'oLinePossessions',
       'dLineScores', 'dLinePoints', 'dLinePossessions', 'redZoneScores',
       'redZonePossessions', 'isHome', 'rosterIds'],
      dtype='object')

In [47]:
tsgHome.dtypes

id                     int64
teamSeasonId           int64
gameId                 int64
source                object
startOnOffense          bool
events                object
updateMoment          object
statusId               int64
scoreTimesOur         object
scoreTimesTheir       object
completionsNumer       int64
completionsDenom       int64
hucksNumer             int64
hucksDenom             int64
blocks                 int64
turnovers              int64
oLineScores            int64
oLinePoints            int64
oLinePossessions       int64
dLineScores            int64
dLinePoints            int64
dLinePossessions       int64
redZoneScores          int64
redZonePossessions     int64
isHome                  bool
rosterIds             object
dtype: object

In [49]:
tsgHome

,id,teamSeasonId,gameId,source,startOnOffense,events,updateMoment,statusId,scoreTimesOur,scoreTimesTheir,...,oLineScores,oLinePoints,oLinePossessions,dLineScores,dLinePoints,dLinePossessions,redZoneScores,redZonePossessions,isHome,rosterIds
0,3937,292,3460,sk-v2,False,"[{""t"":50},{""t"":2,""l"":[12537,11735,11746,11748,...",2024-08-25T03:26:22.427Z,100,"[0, 17, 74, 108, 193, 418, 747, 801, 855, 960,...","[0, 332, 528, 919, 976, 1056, 1245, 1470, 1687...",...,9,18,27,8,19,16,10,15,True,"[11723, 11724, 11725, 11735, 11722, 11730, 117..."

### Upsert

In [82]:

from sqlalchemy import inspect, text, Table, MetaData
from src.utils.postgres.connections import get_postgres_connection

conn = get_postgres_connection()
table_name = 'game_metadata'

metadata = MetaData()
table = Table(table_name, metadata, autoload_with=conn)
table_cols = [col.name for col in table.columns]

In [83]:
from src.utils.dataframe.cleanup import standardize_column_names

df_games = standardize_column_names(df=df_game, case="snake")

In [84]:
table_cols

['id',
 'team_season_id_home',
 'team_season_id_away',
 'status_id',
 'score_home',
 'score_away',
 'live',
 'reg_season',
 'ignore_game',
 'lock',
 'start_timestamp',
 'start_timezone',
 'start_time_tbd',
 'aw_section',
 'score_times_home',
 'score_times_away',
 'ext_game_id',
 'update_timestamp',
 'location_id',
 'ls_game_id',
 'ticket_url',
 'streaming_url',
 'roster_set',
 'roster_set_1',
 'type_id',
 'team_season_home_id',
 'team_season_home_team_id',
 'team_season_home_season_id',
 'team_season_home_division_id',
 'team_season_home_city',
 'team_season_home_abbrev',
 'team_season_home_ulti_analytics_ext_id',
 'team_season_home_final_standing',
 'team_season_home_team_name',
 'team_season_home_team_ext_team_id',
 'team_season_home_team_ls_team_id',
 'team_season_home_team_active',
 'team_season_home_team_primary_hex',
 'team_season_home_team_secondary_hex',
 'team_season_away_id',
 'team_season_away_team_id',
 'team_season_away_season_id',
 'team_season_away_division_id',
 'team_season_away_city',
 'team_season_away_abbrev',
 'team_season_away_ulti_analytics_ext_id',
 'team_season_away_final_standing',
 'team_season_away_team_name',
 'team_season_away_team_ext_team_id',
 'team_season_away_team_ls_team_id',
 'team_season_away_team_active',
 'team_season_away_team_primary_hex',
 'team_season_away_team_secondary_hex']

In [85]:
print(len(set(df_games.columns)))
print(len(df_games.columns))

53
55

In [86]:
dff = df_games.copy()

In [90]:
# -- drop duplicate cols
selected_cols = [dff.columns[i] for i, dup in enumerate(dff.columns.duplicated()) if not dup]

In [93]:
dff.loc[:, ~dff.columns.duplicated(keep='first')]

,id,team_season_id_home,team_season_id_away,status_id,score_home,score_away,live,reg_season,ignore_game,lock,...,team_season_away_city,team_season_away_abbrev,team_season_away_ulti_analytics_ext_id,team_season_away_final_standing,team_season_away_team_name,team_season_away_team_ext_team_id,team_season_away_team_ls_team_id,team_season_away_team_active,team_season_away_team_primary_hex,team_season_away_team_secondary_hex
0,3460,292,295,100,17,16,False,True,False,False,...,Carolina,CAR,None,1,Flyers,flyers,f364b191-1101-4c86-959e-7ac9b2a0909b,True,#003049,#C0C0C0

In [97]:
games_cols = [col for col in df_game.columns if 'time' in col]

In [99]:
df_games[games_cols]

,start_timestamp,start_timezone,start_time_tbd,score_times_home,score_times_away,update_timestamp
0,2024-08-24T19:00:00.000Z,MDT,False,"[0, 17, 74, 108, 193, 418, 747, 801, 855, 960,...","[0, 332, 528, 919, 976, 1056, 1245, 1470, 1687...",2024-08-25T03:26:24.142Z